sudo: false
dist: trusty

cache:
  directories:
  - $HOME/.m2

language: java

jdk:
- oraclejdk8

addons:
  apt:
    packages:
    - oracle-java8-installer

before_install:
- git config user.name "opentracingci"
- git config user.email "opentracingci+opentracing@googlegroups.com"
- git config credential.helper "store --file=.git/credentials"
- echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- ./travis/publish.sh

branches:
  except:
  - /^[0-9]/

env:
  global:
  - secure: n01WuvFTwzpeN7f6gmUHGe5QCyJOminI9xii7gGcGIVpCxw5LrcJTfL3IzYSQRhWRGDc5z/jYbHqeKQQ9ryyvxSFoQk3d/4+w+lUgTl0vISn/beTU/pvGuuY5HZeD1KkcIOv8evd9ekVPFwEOxiQJqDwy/EbL7xSNszZd1UA4sdTWgOLYdd3zGt+FfAN96k7ACOJa8jF1ZPE1R2XJSk3jWKmnsQ7D2VYRI47dJR6h36wxc80FfTFxj8rtc+LLaynrqSFIUiaGQbsZz1aPRJp3Qk+e7Di1A99kyk+OrRtMw6UPPPdWNgFFKtXaQlNwFxD30TBpJ2fqhI+5rF1tcXFKnGR68KWl3BUy9lpt0RyUWXAaEmRJsxj3S7GB0mfC8vCpji6KnjARrsiMAP5n0Yhzw4bqzEK2lIRZ9YqBZjcsJRa7mCCZgAbv2oPdkYJSurVI3rmx9QtsJBqHR57z4lLHfZ4h0HRU1L0CNfoQmR2j0ifmgIO2yVNnO5hcjiHWkvRbkWgGEa/hlcpZgt7c97UzdAo5rkwey1abT5BdVJCnggEoN1hLW6wC1xeFDWDTx4dSx/hcHjxrSdhLIlRJW3FhCIgXEVOa8UNWpxe8BUvBG8UBOCEJTE3bigdfNor72IVvCvabXQI0pQ9SwYV1OsOnGV4EerEWnmjruKEDNeRASw=
  - secure: blYqpwWpzUbSbmMoLtMGZ67vbUFNr9q/4Snlaxkhkp4NT43pQJSpPeq5UUSbTl/1sZ//bZxLIc3MVRwBLx9j3y2u34NKKEu9fznrtVelp/KFlFmygabUdsGoPiEh80J7jLQ04V5Y5qTjew+4BM0c0jgFt7oxzFs80p8OCePOWV0MiRmzCHupMzqcyJP+VMcbZ0HMekpL4HfwPwuTQ0Mrdb1flQDbxrcWTlT1oZcqup61Dqofwgtaciz+A+Ba3QwD5dIrbr21O+/wwoi8y/MZAjH2ht9UGf1BSoyQiHwT74/wU7dodnxfaUJO2SonKIFrYFctsoGt/KZj5E5tMHqD70ILvWE7+9egH5Ise0tgldS+BxKVy494OwjFB8qSAc39l8xsfjBwBwx59YzGvdu3yE8mcPtx5EWll9HANo8MMMwBzN9CoVrngNLa3aZUF+3tH75QAJ6j2Zsh2tQURJv6D2aIEFf/8PFxYJfTR4wUWfMZDeeVPIUtZyEh+qaycfsirkSxaopdh/uTIQqrxxpRlM1s21AWteLYx5waSrp4riWVxpCHjv7zcT1ss9bFcuu/Z08KoeDcfgcyJiwGw3MtVYlOUjxxBJEJSFwRQa8K4jwyC1ERz/Va/qzxGU5i7dwwi2gUREY/vQr9xXbZ8buWoftLDEUJhNpzIJyVDIAMCgw=
  - secure: WDhK8hdTXVG/CyDaqOPDYWOt/8G6KZR0tkaY6m/eYoIb5EEUgI6XG1Kavd0GQMhrkd4AYGj+AqdwgMG7LSlfFWr1TGhlPRVgqOvOd/bZazQv+Hnipo5gY9Y28j1nOkk3JlxQDnMP8xzuDZgzunFOc4ippOP9i94ToY6RbA283u3KZTillPQ2+/yDK1UiwbcLGJyzVFjeyjkSfsTXI5KEs+B7YdAyOUU3gVDu8RzrGigSRWHEDUZH+7zDgDGrMeZ1xJaQdeuj4x8XR0z3iubUZ2vkwzFIQMH8ygZJ/MuLZhKQbTLSSLv6+JJaRcw99H/W9xLSMOzmJWovt07yRCvUm3VQhz4dXuSZY9wMTY+3hgYnYFQlqeT6u+hzdjcfpmxK3wPjaYziwO7VDEq6WjmPdsQ/FVbC4lsJXVWFV/90VB5ahYvTHWx3sYXgqVgv5F/hGiSVV2bPdX45wLG10uytHjAYJUl2oYkqt5KzGvtsfgL18SdBrvRM4+dSiuNC32L3y9pLzp60hskiEUwZuJK9DWSV1Z+BLAs2OzCeKK0bQRzjVA13HWUM+nQCKJrwQ/ak3QIeAzuIjgYUFTTcSc6i9DVTzTHiIP2f7A7Wz6K9ktcUW3VAWf2/BigLBHorEimXYWkzH7RNDfTgWeZ7i5cGSnCa0tdGYzqmpqJmAgoLjqU=
  - secure: VM5lTVrnM29+/tcqnrU9AkryrjJeGgr7Bz6HbKTH9DRgqyn9gsW3tQXnlB/Ai0Yz0ZzMctki/QGn122IU+CUymPyTIEF8fhG5AZsO+qwrqWH8+qHxVs+HuTDt77HYAi8RUdBrpz7FMyMm+QaBefI74xBn7P73eaacendJHu1AcZ5LmbyLwTFZUHbYrhtoxXqhiLqbP2bB2h294xcgAuvG5OXncksivwYpJnAapurnPmd9/u+g9ZOLNcNHSRbNjdI+tavdyHAurB6hV/rq5l+IhWuFC4xulWhMeMAZNDxtQVrIad86YgegQ/2KVBO5eEU9ohXeQgN1qEMg97Lo8yNXfzbr4BFhLC4juPoDjngxLGL1j9oRxiug+HH1Mq+dqVJghkkeL/z1ulvQBT/pnI5YJmSYs8LztTzeMjsLMhhdE9jGwuiQrP5LtY0g/QjU5CnWMh75CQ3DNxCX01mtdIBddD0X8BjL1hHhDotb8XWXizxdKS8rHEwLosg1CPVNJ6nfI/LgUmwOoNuNI0YE89yy2tWpOWmJUpTyGSMcVtrZF0KzlbYjva/Ue2u5QsK+qsaLenmG2DHWqEW/PSvuqCbMHz6oZUKZJEIEm5fTArWLBfG+mY3CNv3F88I5TsS/LXFlB9ErcD87yTJj3DGIJrq7XwUkLq08w3sH8ijy9gd7bg=
  - secure: N9URaqcbRAg0rCcsm3P37phhjd6G+ZI7KAc/0B6W95KysGH/YF7invOpE9J4+j4hPJf74yiQ4O4AQRm4jXnNwosXHJqwuEzCTvFDxTAA2fdnTzUMOIea5JXberIz69DXCVbe29aNW4OWeB2ngdWS+iR8zhnvVXGvB8O89EHjl4QPmhEbBR4NXTer3NPZnEoiirBG6rsg5UICnv3rk2JJX+CwIkvCdHf9kLDjTaPbVYF3MnGTxVvoBKc5ABwzBIeWVhoibse5U3+hr46597Tjo1dvOryyej3syDptrthsuP5+whgeEspTx7Pp9Z3MD0mJ+S2/YD61hRei8L+FqazjDorM6pfOqfp+I+VcHfyl1YwD5cg9vIVchwxAAeiipxJVekACocJ5S9Ou6gG9oqilh/RSDtOc6laxsySE/0WuNPIBS7/ODG54/HCEXeiHG2uFxh1VlgFF1x3gDTYPKqq6vrud0GjDcsf6unf5anc84o/zHsRD9dbE89uEWnM5rYVtIyhxyGFyoaaEQZIFFjFA3UB5pt8Evx3pvdSmrmyzbYcbAsC1Vx1teKwm3O7SYyG48wlcfpGbHPI5NB6XxQwSxuSMpXTqQRt6LvpsBxwZQ2pXLIC6jr0S4f9RQWJjRzfJnN3bvZtIqJgkrkCcxCzbQ7qHNzNoT2vBXXCFyVBgqnI=
